---
app:
  is_debug: true
  id: prod-service
  name: Production Service
  log_level: trace
  admin:
    email: admin@taod.ru
    password: "123"

grpc:
  ip: 0.0.0.0
  port: 30000

http:
  ip: 0.0.0.0
  port: 30001
  read_timeout: 15s
  write_timeout: 15s
  cors:
    debug: true
    allowed_methods: ["GET", "POST", "PATCH", "PUT", "OPTIONS", "DELETE"]
    allowed_origins:
      - "http://localhost:3000"
    allow_credentials: true
    allowed_headers:
      - "Authorization"
      - "Location"
      - "Charset"
      - "Access-Control-Allow-Origin"
      - "Content-Type"
      - "Origin"
      - "Accept"
      - "Content-Length"
      - "Accept-Encoding"
      - "X-CSRF-Token"
    options_passthrough: true
    exposed_headers:
      - "Location"
      - "Authorization"
      - "Content-Disposition"

postgresql:
  host: 0.0.0.0
  port: "5432"
  username: postgres
  password: postgres
  database: prodservice